### ISSUE TITLE
Checking with Sean & Eddie

### ISSUE THREAD

**Issue by lcolladotor** [LieberInstitute/recount3-docs#2]
Hi @metamaden, @eddieimada, 

Am I missing any GitHub repos or project websites that you would like to list in either https://github.com/LieberInstitute/recount3-docs/blob/master/07_software.Rmd#L28 or https://github.com/LieberInstitute/recount3-docs/blob/master/08_analysis.Rmd?

It's becoming harder to keep track of where everything lives as the recount world keeps expanding :P 

If I'm missing any links, please let me know or feel free to edit the files directly. The website will update automatically using GitHub actions.

Best,
Leo

**Comment by eddieimada** [comment]
Everything seems right on my end. Congrats on this great work that keeps growing!

**Comment by metamaden** [comment]
Hi @lcolladotor, sorry for taking a while to get back -- I don't get many mentions on GitHub, and don't monitor them too often. Thanks for including the link to the `recountmethylation` Bioconductor package. That's all there is for now, but we'll probably introduce a few more related resource links that can be shared later this year. Thanks!
