### ISSUE TITLE
URLs not loading

### ISSUE THREAD

**Issue by brigmecham** [LieberInstitute/recount3-docs#3]
Hello,

Thanks for putting together such a great resource!

Via curl or my web browser I'm trying to access some of the URLs listed in this file and they are not loading.  

https://github.com/LieberInstitute/recount3-docs/blob/master/docs/recount3_raw_project_files_with_default_annotation.csv

Here's an example url: http://idies.jhu.edu/recount3/data/human/data_sources/sra/gene_sums/65/SRP107565/sra.gene_sums.SRP107565.G026.gz

Unfortunately it looks like the file is unavailable.   Have they moved or am I doing something wrong?

Any help is much appreciated!

**Comment by lcolladotor** [comment]
Hi,

This might have been related to https://github.com/LieberInstitute/recount3/issues/29.

It should be resolved now.

Best,
Leo
